# Generated by Django 5.0.14 on 2026-09-21 17:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(max_length=100, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='PKR', max_length=10)),
                ('method', models.CharField(choices=[('card', 'Credit / Debit Card (Visa/MasterCard)'), ('bank', 'Bank Transfer / SWIFT'), ('1link', '1Link / Raast Online'), ('cash', 'Concierge Cash on Arrival')], default='card', max_length=30)),
                ('status', models.CharField(choices=[('pending', 'Pending Verification'), ('successful', 'Successful'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='bookings.booking')),
            ],
        ),
    ]
